############################################################################################
# Market YAML config.
#
# - All fields are mandatory unless stated otherwise.
# - Multiple market blocks can be listed.
# - The indentation levels are significant in YAML: https://en.wikipedia.org/wiki/YAML
#
# NOTE: XXBT is the same currency code as BTC for Bitcoin on Kraken exchange.
############################################################################################
---
markets:


  - id: XBTEUR
    name: XBT/EUR
    baseCurrency: XXBT
    counterCurrency: ZEUR
    enabled: true
    tradingStrategyId: alwaysHighStrategy
  - id: ETHEUR
    name: ETH/EUR
    baseCurrency: XETH
    counterCurrency: ZEUR
    enabled: false
    tradingStrategyId: alwaysHighStrategy  
